### PR TITLE
Adding tests for handling poetic mode parameters with assignment

### PR DESCRIPTION
**Pull request by JohnnysRibeiro**
The issue https://github.com/Kuniri/kuniri/issues/95 was actually already implemented but there were no tests for it. 

This closes issue https://github.com/Kuniri/kuniri/issues/95

### CODE REVIEW

**Comment by rodrigosiqueira** [comment]
Hey dude, I have a suggestion to you. Try to implement this test:

``` ruby
it "String parameter." do
    input = 'def xpto_method x="b"       '
   methodOne = @functionBehaviorRuby.get_function(input)
   expect(methodOne.parameters).to match_array([{"x"=>"b"}])
end
```

Try it :)

**Comment by JohnnysRibeiro** [comment]
shouldn't the matched array be

match_array([{"x"=>""b""}])

?

2015-09-11 23:07 GMT-03:00 Rodrigo Siqueira de Melo <
notifications@github.com>:

**Comment by JohnnysRibeiro** [comment]
sorry, it should be something like this ([{"x"=>"\"b\""}]), right?

2015-09-12 0:17 GMT-03:00 João Paulo Ribeiro johnnys.ribeiro@gmail.com:

**Comment by rodrigosiqueira** [comment]
Yes, you can try: "x" = "\"b\"", "x" = '"b"', "x = "[]", etc...
My point is: If we use something different of number, kuniri cannot capture the correct value.

**Comment by rodrigosiqueira** [comment]
I'm not complete sure, but I believe that handling_default_parameter() in function_behaviour_ruby.rb should have a regex like: 

``` ruby
=\s*\w*|(['"])(?:(?!\1).)*\1|(\[\])|(\{\})

-->Match: x= 3, y = [], k = "u", y = 7, m = {}, i='huum'
-->Not match: x= 3, y = [], k = "u", y = 7, m = {}, i='huum', t = [1,2,3]
```

Ps.: This is just the beginning of the regex, you have to improve it ;)

**Pull request merged**
